apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.abVodService.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.service.abVodService.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.service.abVodService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.abVodService.name }}
    spec:
      containers:
      - name: {{ .Values.service.abVodService.name }}
        image: {{ .Values.image.baseRepositoryUrl }}{{ .Values.service.abVodService.name }}{{ .Values.service.abVodService.deployment.imageVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.resource.requests.cpu }}
            memory: {{ .Values.resource.requests.memory }}
          limits:
            cpu: {{ .Values.resource.limits.cpu }}
            memory: {{ .Values.resource.limits.memory }}
        ports:
        - containerPort: {{ .Values.service.abVodService.ports.containerPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.service.livenessProbe.httpGet.path }}
            port: {{ .Values.service.abVodService.ports.containerPort }}
          initialDelaySeconds: {{ .Values.service.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.service.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.service.readinessProbe.httpGet.path }}
            port: {{ .Values.service.abVodService.ports.containerPort }}
          initialDelaySeconds: {{ .Values.service.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.service.readinessProbe.periodSeconds }}