apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.autoscaling.abVodService.name }}
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.service.abVodService.name }}
  minReplicas: {{ .Values.autoscaling.abVodService.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.abVodService.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.autoscaling.abVodService.targetCPUUtilizationPercentage }}