apiVersion: v1
kind: PersistentVolume
metadata:
  name: ab-efs-svc-pv
  namespace: dev
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ab-efs-svc-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-cc81ec78