# Default values for muselive-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

release:
  managedBy: Helm
  name: ab-dev
  namespace: default

namespace: dev

image:
  baseRepositoryUrl: 353380520333.dkr.ecr.us-east-1.amazonaws.com/
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: NodePort
  healthCheckPath: "/status"
  livenessProbe:
    httpGet:
      path: "/status"
    initialDelaySeconds: 10
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: "/status"
    initialDelaySeconds: 10
    periodSeconds: 10
  abApiGateway:
    name: ab-api-gateway
    deployment:
      imageVersion: ":v0.1.5"
      replicas: 1
    ports:
      port: 3000
      targetPort: 3000
      containerPort: 3000
      protocol: TCP
  abVodService:
    name: ab-vod-service
    deployment:
      imageVersion: ":v0.1.2"
      replicas: 1
    ports:
      port: 3001
      targetPort: 3001
      containerPort: 3001
      protocol: TCP
  abEfsService:
    name: ab-efs-service
    deployment:
      imageVersion: ":v0.1.2"
      replicas: 1
    ports:
      port: 3002
      targetPort: 3002
      containerPort: 3002
      protocol: TCP
    volumeMount:
      name: persistent-storage
      mountPath: /usr/app/public
    volumes:
      name: persistent-storage
      persistentVolumeClaim:
        claimName: ab-efs-svc-pvc

resource:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

autoscaling:
  abApiGateway:
    name: ab-api-gateway-hpa
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
  abVodService:
    name: ab-vod-service-hpa
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
  abEfsService:
    name: ab-efs-service-hpa
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}